---
apiVersion: v1
kind: Service
metadata:
  name: alexwitt-hw7-worker-service
  labels:
    username: alexwitt
    env: test
spec:
  type: ClusterIP
  selector:
    username: alexwitt
    env: test
    app: alexwitt-hw7-worker
