---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alexwitt-hw7-redis-pvc
  labels:
    username: alexwitt
    env: hw7
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
