---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexwitt-test-redis-deployment
  labels:
    app: alexwitt-test-redis
    username: alexwitt
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexwitt-test-redis
  template:
    metadata:
      labels:
        app: alexwitt-test-redis
        username: alexwitt
        env: test
    spec:
      containers:
      - name: alexwitt-test-redis
        image: redis:5.0.0
        volumeMounts:
        - name: alexwitt-test-redis-pvc
          mountPath: "/data"
        ports:
        - name: redis
          containerPort: 6379
      volumes:
      - name: alexwitt-test-redis-pvc
        persistentVolumeClaim:
          claimName: alexwitt-test-redis-pvc
