---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexwitt-test-flask-deployment
  labels:
    app: alexwitt-test-flask
    username: alexwitt
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alexwitt-test-flask
  template:
    metadata:
      labels:
        app: alexwitt-test-flask
        username: alexwitt
        env: test
    spec:
      containers:
      - name: alexwitt-test-flask
        image: alexwitt/midterm
        ports:
        - name: flask
          containerPort: 5000
        env:
        - name: "REDIS_HOST"
          value: "10.96.8.238"
