package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")


py_library(
    name = "api",
    srcs = ["api.py"],
)

py_library(
    name = "jobs",
    srcs = ["jobs.py"],
)

py_library(
    name = "worker",
    srcs = ["worker.py"],
)
