version: "3"
services:
  web:
    container_name: alexwitt_midterm
    build: .
    ports:
      - "5038:5000"
  redis:
    image: "redis:alpine"
    volumes:
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf
