---
apiVersion: v1
kind: Service
metadata:
  name: alexwitt-hw7-flask-service
  labels:
    username: alexwitt
    env: hw7
spec:
  type: ClusterIP
  selector:
    username: alexwitt
    env: hw7
    app: alexwitt-hw7-flask
  ports:
  - name: flask
    port: 5000
    targetPort: 500
