---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    greeting: personalized
spec:
  containers:
    - name: hello
      image: ubuntu:18.04
      command: ['sh', '-c', 'echo "Hello, $NAME from IP $POD_IP!" && sleep 3600']
      env:
        - name: "NAME"
          value: "Alex"
        - name: "POD_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
